### ISSUE TITLE
Client crash when interacting with inventory items

### ISSUE THREAD

**Issue by KodinLanewave** [Griefed/Survive-Create-Prosper-4#3]
* **Please tell us about your environment:**

   - Survive Create Prosper version: 1.16.5-4.6.9
   - Operating system: Windows 10 Version 1909
   - Java version: 1.8.0_291-b10
   
* **Logs:**

  - crash-log: [Pastebin] https://pastebin.com/6KadwwZW

* **What is the current behavior?**

Semi-regular crashes when mousing over or transferring items in inventory to a chest.  So far the most recent was holding shift over bitumen collected from bitumen ore.  Same type error in all cases.

The game crashed whilst rendering screen
Error: java.lang.ClassCastException: net.minecraft.nbt.StringNBT cannot be cast to net.minecraft.nbt.CompoundNBT
Exit Code: -1

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **Other information / Questions**

**Comment by Griefed** [comment]
Thanks for opening this issue!
I'll try to replicate it and see what I can do.

**Comment by Griefed** [comment]
Alright, so I can definitely replicate it. Anytime I hover over the Akashic Tome, from the same mod, and press the shift key, the game crashes with the `java.lang.ClassCastException: net.minecraft.nbt.StringNBT cannot be cast to net.minecraft.nbt.CompoundNBT` you mentioned. This is not limited to chests, because it happens in the players inventory, too. See https://haste.zneix.eu/ipolakiqoj.rb

Others have reported similar behaviour over on the AkashicTome repository at https://github.com/Vazkii/AkashicTome/issues/63.

**Comment by Griefed** [comment]
More test results! The crash does **not** occur in the older version of AkashicTome, namely 1.4-15.

**Comment by Griefed** [comment]
Update of Survive Create Prosper 4 version 4.6.10a, with a downgraded version of Akashic Tome among other small things, is available at https://www.curseforge.com/minecraft/modpacks/survive-create-prosper-4/files/3304936
Server pack https://www.curseforge.com/minecraft/modpacks/survive-create-prosper-4/files/3304959.

Please let me know if this fixed the issue on your end as well.

**Comment by KodinLanewave** [comment]
Sweet! I'll test later today. Your turnaround is impressive.

**Comment by Griefed** [comment]
I've got a GitHub related channel on my Discord server which posts messages whenever something happens on certain repositories, hence the quick reaction. Your crash report also proved **very** helpful. Without it, it would have taken much longer to figure out, so thank you very much for including that.
Happy mining!
